name: 问题反馈
description: 反馈你遇到的问题
title: "[BUG]"
labels: bug

body:
  - type: textarea
    id: describe
    attributes:
      label: |
        问题描述
      description: |
        清晰简洁地描述问题。
    validations:
      required: true

  - type: textarea
    id: recurrence
    attributes:
      label: |
        问题复现
      description: |
        步骤示例
        问题复现步骤：
        1. 前往“...”
        2. 点击“....”
        3. 滚动到“....”
        4. 出现错误
    validations:
      required: true

  - type: textarea
    id: expectation
    attributes:
      label: |
        预期行为
      description: |
        描述你期望发生的正确结果。
    validations:
      required: true

  - type: textarea
    id: smartphone-info
    attributes:
      label: |
        手机信息
      description: |
        示例：
        设备: Xiaomi
        系统: HyperOS 2.0.200, Android 15
        InstallerX 版本: latest alpha/latest stable
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: |
        屏幕截图或录屏
      description: |
        如适用，可提供截图或录屏辅助说明。
    validations:
