name: 🐞 Bug Report/问题反馈
description: Report A Bug You Saw It In The App
title: "[BUG]"
labels: bug

body:
  - type: textarea
    id: describe
    attributes:
      label: |
        Describe the bug
      description: |
        Tell Us What Happened Before The Bug Show Up.
    validations:
      required: true

  - type: textarea
    id: recurrence
    attributes:
      label: |
        To Reproduce
      description: |
        Example of Problem Reproduction Steps:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See Error
    validations:
      required: true

  - type: textarea
    id: expectation
    attributes:
      label: |
        Expected behavior
      description: |
        What Did You Expected To Happen ?
    validations:
      required: true

  - type: textarea
    id: smartphone-info
    attributes:
      label: |
        Smartphone Info
      description: |
        example:\
        Device: Xiaomi\
        OS: HyperOS 2.0.200, Android 15\
        InstallerX Version: Latest Alpha/Latest Stable
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: |
        Screenshots or ScreenCAP
      description: |
         Add Screenshots Or ScreenCAP To Help Explain Your Problem.
    validations:
