name: 功能建议
description: 提供一个建议
title: "[Feature Request]"
labels: enhancement

body:
  - type: textarea
    id: feature-description
    attributes:
      label: |
        新功能描述
      description: |
        清晰地描述所你想要的新功能或改进\
        清晰地描述您考虑过的其他替代方案\
        例如:\
        我在使用中遇到了什么场景，我希望添加什么功能, 以及这个功能的作用是什么\
        我考虑过其他方案，比如...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: |
        屏幕截图或录屏
      description: |
        如适用，可提供截图或录屏辅助说明。
    validations:
